### ISSUE TITLE
How to run this project

### ISSUE THREAD

**Issue by liuqi8827** [JohanSamir/revisiting_rainbow#8]
Thanks for your great work.

I have installed Revisiting Rainbow's dependencies and MinAtar.
How to run project?

Thanks a lot!

**Comment by johanobandoc** [comment]
Hi liuqi8827,

Thanks! :) I will upload a colab file explaining how to run experiments.

**Comment by liuqi8827** [comment]
@JohanSamir 
Thank you.

**Comment by johanobandoc** [comment]
Hi @liuqi8827,

I've already uploaded the colab file explaining how to run experiments. Check it out and let me know if you any questions :)

**Comment by liuqi8827** [comment]
@JohanSamir 

Thanks for your reply.

I wiil try to run experiments.

Thanks a lot!
